### ISSUE TITLE
Update documentation for dev environment

### ISSUE THREAD

**Issue by AtaGowani** [arborrow/montserrat#215]
## Description
Update the documentation to include the basic steps needed to get started and running.

**Comment by AtaGowani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update documentation on how to build and work on the frontend](https://trello.com/c/exVJQU3w/8-update-documentation-on-how-to-build-and-work-on-the-frontend)

**Comment by arborrow** [comment]
I'm running Ubuntu 18.04 - php 7.2. Regarding step 2, I installed composer via apt install composer. Afterwards, I needed to install the mbsring, curl and dom php extensions in order for composer install to run. We may want to document that in the readme file.

**Comment by arborrow** [comment]
To get npm install to run I also needed libpng-dev - see https://github.com/imagemin/pngquant-bin/issues/96:

So prior to running composer install and npm install I would make note that folks should also run:
sudo apt install php-mbstring php-curl php-dom libpng-dev

**Comment by arborrow** [comment]
Let's add also specify that we need vagrant 2.2+. In order to run the final seed, I needed to temporarily commend out the google_client_id in the .env to avoid the permissions error. Then after running the RoleUserTableSeeder I went back and uncommented it and everything worked. There may be another way of checking the status with an if statement if we wanted to make it just a little smoother but this is much improved from where we were before.
