### ISSUE TITLE
Assumption about user leading to error

### ISSUE THREAD

**Issue by AtaGowani** [arborrow/montserrat#272]
## Description
Assumes that the logged in user is associated with a contact in which the USER (logged in authenticated user) has an email that corresponds to an email address in the email table that is associated with a contact.
## Screenshot
<img width="1440" alt="screen shot 2019-01-06 at 10 36 37 pm" src="https://user-images.githubusercontent.com/19475663/50749308-a4c3ad80-1203-11e9-805a-a58320d158f2.png">

## Possible Fix
Automatically create a contact when a new user is added and populate the email.

**Comment by arborrow** [comment]
Just a quick note to document the intended behavior. 

Part of generating an AGC Acknowledgment letter is to create a touchpoint that the letter has been created and sent. Polanco presumes that the currently authenticated **user** has a record in the **contact** table with a **corresponding email address** in order to automatically set the touched by field. 

It is possible that an authenticated user **does not** have a contact record with the email address populated. In such cases, that user is unable to view the AGC acknowledgement letter and will be redirected to the page that they came from and given an error message that they need to create a contact record associating the authenticated user's email address with a contact record. The user-contact association thus allows Polanco to autocomplete the touched by field based on the authenticated user. 

For unit testing, the "happy path" will create a new user and then add the user's email address to a contact record to ensure that the unit test passes. A separate unit test creates a new user but does not associate the email address with a contact record. The unit test then sets the from page to the donation show blade for the generated payment and tests to make sure that the request redirects back to the donation show blade and that the request produces a flash message.
